{
  parserClass="com.simpleplugin.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.simpleplugin.psi"
  psiImplPackage="com.simpleplugin.psi.impl"

  elementTypeHolderClass="com.simpleplugin.psi.SimpleTypes"
  elementTypeClass="com.simpleplugin.psi.SimpleElementType"
  tokenTypeClass="com.simpleplugin.psi.SimpleTokenType"

  psiImplUtilClass="com.simpleplugin.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= (
    NEW_SLIDE_HORIZONTAL
    |NEW_SLIDE_VERTICAL

    |NEW_PRESENTER_NOTES

    |NEW_BOOK_NOTES
    |WHITESPACE_BOOK_NOTES

    |REGULAR_CHARS
    |SLIDES_COMANDO_ESPECIAL
    |SLIDES_NOTES
    |SLIDES_NOTES_BOLD_ITALICS
    |SLIDES_NOTES_BOLD
    |SLIDES_NOTES_ITALICS
    |SLIDES_BOLD_ITALICS
    |SLIDES_BOLD
    |SLIDES_ITALICS
    |SLIDES_HEADER
    |SLIDES_NOTES_HEADER
    |SLIDES_IMAGEM_OU_LINK
    |SLIDES_CODE_SPAN
    |SLIDES_REVEAL_HTML_CONFIG
    |SLIDES_TUDOMAIS
)*
/*
property ::= ((KEY|BOLD)+ SEPARATOR VALUE?)|KEY {
    pin=3
    recoverWhile="recover_property"
    mixin="com.simpleplugin.psi.impl.SimpleNamedElementImpl"
    implements="com.simpleplugin.psi.SimpleNamedElement"
    methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}

private recover_property ::= !(KEY|SEPARATOR|BOLD|NEW_SLIDE_HORIZONTAL|NEW_SLIDE_VERTICAL|NEW_SLIDE_NOTES_DIVIDER)
*/